haytunes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    path('category/create/', views.CategoryCreate.as_view(), name='category_create'),
    path('category/<int:pk>/update/', views.CategoryUpdate.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', views.CategoryDelete.as_view(), name='category_delete'),
    path('products/', views.ProductListView.as_view(), name='products'),
    path('product/<uuid:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('product/create/', views.ProductCreate.as_view(), name='product_create'),
    path('product/<uuid:pk>/update/', views.ProductUpdate.as_view(), name='product_update'),
    path('product/<uuid:pk>/delete/', views.ProductDelete.as_view(), name='product_delete'),
]

webdownload/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from haytunes.views import signup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('haytunes/', include('haytunes.urls')),
    path('', RedirectView.as_view(url='/haytunes/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', signup, name='signup'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

haytunes/models.py
import uuid

from django.core.validators import MinValueValidator, RegexValidator
from django.db import models
from django.contrib.auth.models import User, AbstractUser

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    credit = models.DecimalField(null=True, max_digits=8, decimal_places=2, validators=[MinValueValidator(0.001)])

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Category(models.Model):
    name = models.CharField(max_length=30, validators=[
        RegexValidator(regex='^[a-zA-Z]*$', message='Name must be Alphabetic', code='invalid_name')])

    class Meta:
        permissions = (("can_admin_content", "Admin content in page"),)

    def get_absolute_url(self):
        return reverse('category-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular product across')
    title = models.CharField(max_length=30)
    price = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0.001)])
    author = models.CharField(max_length=100)
    LOAN_TYPE = (
        ('i', 'Image'),
        ('a', 'Audio'),
        ('v', 'Video'),
    )
    type = models.CharField(max_length=1, choices=LOAN_TYPE, help_text="Types of contents")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    #owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    owner = models.ManyToManyField(User, help_text='Select an owner for this product.', blank=True)
    content = models.FileField(upload_to='product')

    def get_absolute_url(self):
        return reverse('product-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.id} ({self.title})'

    def display_owner(self):
        return ', '.join(owner.first_name for owner in self.owner.all()[:3])

    display_owner.short_description = 'Owner'

haytunes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from haytunes.models import Profile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('credit',)

haytunes/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db import transaction
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext as _

# Create your views here.
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from haytunes.forms import SignUpForm, ProfileForm, UserForm
from haytunes.models import Category, Product


def index(request):
    products_audio = Product.objects.filter(type='a')[:6]
    products_video = Product.objects.filter(type='v')[:6]
    products_image = Product.objects.filter(type='i')[:6]
    context = {'products_audio': products_audio, 'products_video': products_video, 'products_image': products_image}

    return render(request, 'index.html', context)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


def profile(request):
    return render(request, 'haytunes/profile.html')


@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        #profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid():
            user_form.save()
            #profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            return redirect('profile')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        #profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'haytunes/update_profile.html', {
        'user_form': user_form,
        #'profile_form': profile_form
    })


class CategoryListView(PermissionRequiredMixin, generic.ListView):
    permission_required = 'haytunes.can_admin_content'
    model = Category


class CategoryDetailView(PermissionRequiredMixin, generic.DetailView):
    permission_required = 'haytunes.can_admin_content'
    model = Category


class CategoryCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'haytunes.can_admin_content'
    model = Category
    fields = '__all__'


class CategoryUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'haytunes.can_admin_content'
    model = Category
    fields = '__all__'


class CategoryDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'haytunes.can_admin_content'
    model = Category
    success_url = reverse_lazy('categories')


class ProductListView(generic.ListView):
    model = Product
    paginate_by = 10


class ProductDetailView(generic.DetailView):
    model = Product


class ProductCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'haytunes.can_admin_content'
    model = Product
    fields = ['title', 'price', 'author', 'type', 'category', 'owner', 'content']


class ProductUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'haytunes.can_admin_content'
    model = Product
    fields = ['title', 'price', 'author', 'type', 'category', 'owner', 'content']


class ProductDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'haytunes.can_admin_content'
    model = Product
    success_url = reverse_lazy('products')

haytunes/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    {% block title%}<title>haytunes</title>{% endblock %}

    {% load static %}
    <!-- Favicon -->
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    <!-- Preloader -->
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="lds-ellipsis">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <!-- ##### Header Area Start ##### -->
    <header class="header-area">
        <!-- Navbar Area -->
        {% block navbar %}{% endblock %}
    </header>
    {% block hero-area %}{% endblock %}
    <!-- ##### Header Area End ##### -->

    <!-- ##### Breadcumb Area Start ##### -->
    {% block pagina_titulo_area %}
        <section class="breadcumb-area bg-img bg-overlay" style="background-image: url(/static/img/bg-img/breadcumb3.jpg);">
            <div class="bradcumbContent">
                {% block pagina_titulo %}{% endblock %}
            </div>
        </section>
    {% endblock %}
    <!-- ##### Breadcumb Area End ##### -->

    {% block content %}{% endblock %}
            <div class="container">
                {% block pagination %}
                    {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}
                                <span class="page-current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endif %}
                {% endblock %}
            </div>

    <!-- ##### Footer Area Start ##### -->

    {% block footer %}
    <footer class="footer-area">
        <div class="container">
            <div class="row d-flex flex-wrap align-items-center">
                <div class="col-12 col-md-6">
                    <a href="#"><img src="/static/img/core-img/logo.png" alt=""></a>
                    <p class="copywrite-text"><a href="#"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>

                <div class="col-12 col-md-6">
                    <div class="footer-nav">
                        <ul>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Albums</a></li>
                            <li><a href="#">Events</a></li>
                            <li><a href="#">News</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    {% endblock %}
    <!-- ##### Footer Area Start ##### -->

    <!-- ##### All Javascript Script ##### -->
    <!-- jQuery-2.2.4 js -->
    {% load static %}
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/bootstrap/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <!-- All Plugins js -->
    <script src="{% static 'js/plugins/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
</body>

</html>

haytunes/templates/base_nav.html
{% load static %}
<div class="oneMusic-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Menu -->
                    <nav class="classy-navbar justify-content-between" id="oneMusicNav">

                        <!-- Nav brand -->
                        <a href="{% url 'index' %}" class="nav-brand"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">

                            <!-- Close Button -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul>
                                    <li><a href="{% url 'index' %}">Home</a></li>
                                    <li><a href="{% url 'index' %}">Buscar por Nombre</a></li>
                                    <li><a href="#">Buscar por codigo</a></li>
                                    <li><input type="search"></li>
                                </ul>

                                <!-- Login/Register & Cart Button -->
                                <div class="login-register-cart-button d-flex align-items-center">
                                    <!-- Login/Register -->
                                    {% if user.is_authenticated %}
                                        <div class="login-register-btn mr-50">
                                            <a id="loginBtn" href="{% url 'profile' %}">Perfil</a>
                                        </div>
                                        <div class="login-register-btn mr-50">
                                            <a id="logoutBtn" href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
                                        </div>
                                    {% else %}
                                        <div class="login-register-btn mr-50">
                                            <a id="loginBtn" href="{% url 'login' %}?next={{ request.path }}">Login</a>
                                        </div>
                                        <div class="login-register-btn mr-50">
                                            <a id="signupBtn" href="{% url 'signup' %}">Register</a>
                                        </div>
                                    {% endif %}

                                    <!-- Cart Button -->
                                    <div class="cart-btn">
                                        <p><span class="icon-shopping-cart"></span> <span class="quantity">1</span></p>
                                    </div>
                                </div>
                            </div>
                            <!-- Nav End -->

                        </div>
                    </nav>
                </div>
            </div>
</div>

haytunes/templates/haytunes/category_confirm_delete.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Delete Category</h1>
    <p>Are you sure you want to delete the category: {{ category }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
{% endblock %}

haytunes/templates/haytunes/category_detail.html
{% extends 'base_generic.html' %}
<header class="header-area">
    {% block navbar %}
        {% include 'base_nav.html' %}
    {% endblock %}
</header>
{% block pagina_titulo %}
    <p>See what’s new</p>
    <h2>Categoría: {{ category }}</h2>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
    <div class="single-artists d-flex justify-content-center align-items-center wow fadeInUp mt-0 mb-15 m-auto" data-wow-delay="100ms">
        <a href="{% url 'product_create' %}" class="btn oneMusic-btn mt-30">Ingresar Nuevo Producto</a>
        <a href="{% url 'categories' %}" class="btn oneMusic-btn mt-30">Ver todas las Categorías </a>
        <a href="{% url 'category_create' %}" class="btn oneMusic-btn mt-30">Crear Categoría </a>
    </div>
  <table class="table text-center">
      <thead class="thead-dark">
          <tr>
              <th>Titulo</th>
              <th>Tipo</th>
              <th>Categoría</th>
              <th>Código</th>
              <th>Ver</th>
              <th>Eliminar</th>
          </tr>
      </thead>
      <tbody>
          {% for product in category.product_set.all %}
              <tr>
                <td>{{ product.title }}</td>
                <td>{{ product.get_type_display }}</td>
                <td>{{ product.category }}</td>
                <td>{{ product.id }}</td>
                <td><a href="{{ product.get_absolute_url }}">Click</a></td>
                 <td><a href="{{ product.get_absolute_url }}/delete">X</a></td>
              </tr>
          {% endfor %}
      </tbody>
  </table>
    <div class="single-artists d-flex justify-content-center align-items-center wow fadeInUp mt-0 mb-15 m-auto" data-wow-delay="100ms">
        <a href="{% url 'categories' %}" class="btn oneMusic-btn mt-30">Regresar </a>
    </div>
</div>
{% endblock %}

haytunes/templates/haytunes/category_form.html
{% extends 'base_generic.html' %}
<header class="header-area">
    {% block navbar %}
        {% include 'base_nav.html' %}
    {% endblock %}
</header>
{% block pagina_titulo %}
    <p>See what’s new</p>
    <h2>Crear Categoría</h2>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
        <br>
        <form action="" method="post" enctype="multipart/form-data" class="text-center">
        {% csrf_token %}
        <table class="table text-center">
            <thead class="thead-dark">
          <tr>
              <th></th>
              <th></th>

          </tr>
      </thead>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" class="btn oneMusic-btn mt-30">
        </form>
    <div class="single-artists d-flex justify-content-center align-items-center wow fadeInUp mt-0 mb-15 m-auto" data-wow-delay="100ms">
        <a href="{% url 'categories' %}" class="btn oneMusic-btn mt-30">Regresar </a>
    </div>
    </div>
    <hr>
{% endblock %}

haytunes/templates/haytunes/category_list.html
{% extends 'base_generic.html' %}
<header class="header-area">
    {% block navbar %}
        {% include 'base_nav.html' %}
    {% endblock %}
</header>
{% block pagina_titulo %}
    <p>See what’s new</p>
    <h2>Todas las Categorías</h2>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
    <div class="single-artists d-flex justify-content-center align-items-center wow fadeInUp mt-0 mb-15 m-auto" data-wow-delay="100ms">
        <a href="{% url 'categories' %}" class="btn oneMusic-btn mt-30">Ver todas las Categorías </a>
        <a href="{% url 'category_create' %}" class="btn oneMusic-btn mt-30">Crear Categoría </a>
    </div>
  <table class="table text-center">
      <thead class="thead-dark">
          <tr>
              <th>Nombre</th>
              <th>Ver</th>
              <th>Editar</th>
              <th>Eliminar</th>
          </tr>
      </thead>
      <tbody>
      {% if category_list %}
          {% for category in category_list %}
              <tr>
                <td>{{ category }}</td>
                <td><a href="{{ category.get_absolute_url }}">Click</a></td>
                  <td><a href="{{ category.get_absolute_url }}/update">Editar</a></td>
                 <td><a href="{{ category.get_absolute_url }}/delete">X</a></td>
              </tr>
          {% endfor %}
      {% endif %}
      </tbody>
  </table>
</div>
{% endblock %}

haytunes/templates/haytunes/product_confirm_delete.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Delete Prodcut</h1>
    <p>Are you sure you want to delete the product: {{ product }}?</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
{% endblock %}

haytunes/templates/haytunes/product_detail.html
{% extends 'base_generic.html' %}
<header class="header-area">
    {% block navbar %}
        {% include 'base_nav.html' %}
    {% endblock %}
</header>
{% block pagina_titulo %}
    <p>See what’s new</p>
    <h2>Producto: {{ product.title }}</h2>
{% endblock %}
{% block content %}
    <br>
    <br>
    <div class="container">
    <table class="table text-center">
      <thead class="thead-dark">
          <tr>
              <th>Titulo</th>
              <th>Tipo</th>
              <th>Categoría</th>
              <th>Autor</th>
              <th>Código</th>
              <th>Propietario/s</th>
              <th>Precio</th>
              <th>Ver</th>
              {% if perms.catalog.can_mark_returned %}
                    <th>Editar</th>
                    <th>Eliminar</th>
              {% endif %}

          </tr>
      </thead>
      <tbody>
            <tr>
                <td>{{ product.title }}</td>
                <td>{{ product.get_type_display }}</td>
                <td>{{ product.category }}</td>
                <td>{{ product.author }}</td>
                <td>{{ product.id }}</td>
                <td>{% for owner in product.owner.all %} {{ owner }}{% if not forloop.last %}, {% endif %} {% endfor %}</td>
                <td>{{ product.price }}</td>
                <td><a href="/media/{{ product.content }}">Ver</a></td>
                {% if perms.catalog.can_mark_returned %}
                    <td><a href="{{ product.get_absolute_url }}/update">Editar</a></td>
                    <td><a href="{{ product.get_absolute_url }}/delete">X</a></td>
                {% endif %}
              </tr>
      </tbody>
    </table>
    <div class="single-artists d-flex justify-content-center align-items-center wow fadeInUp mt-0 mb-15 m-auto" data-wow-delay="100ms">
        <a href="{% url 'products' %}" class="btn oneMusic-btn mt-30">Regresar </a>
    </div>
    </div>
{% endblock %}

haytunes/templates/haytunes/product_form.html
{% extends 'base_generic.html' %}
<header class="header-area">
    {% block navbar %}
        {% include 'base_nav.html' %}
    {% endblock %}
</header>
{% block pagina_titulo %}
    <p>See what’s new</p>
    <h2>Ingresar/Editar producto</h2>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
        <br>
        <form action="" method="post" enctype="multipart/form-data" class="text-center">
        {% csrf_token %}
        <table class="table text-center">
            <thead class="thead-dark">
          <tr>
              <th>Titulo</th>
              <th>Tipo</th>

          </tr>
      </thead>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" class="btn oneMusic-btn mt-30">
        </form>
    <div class="single-artists d-flex justify-content-center align-items-center wow fadeInUp mt-0 mb-15 m-auto" data-wow-delay="100ms">
        <a href="{% url 'products' %}" class="btn oneMusic-btn mt-30">Regresar </a>
    </div>
    </div>
    <hr>
{% endblock %}

haytunes/templates/haytunes/product_list.html
{% extends 'base_generic.html' %}
<header class="header-area">
    {% block navbar %}
        {% include 'base_nav.html' %}
    {% endblock %}
</header>
{% block pagina_titulo %}
    <p>See what’s new</p>
    <h2>Todos los productos</h2>
{% endblock %}
{% block content %}
    <div class="container">
        <br>

    {% if perms.catalog.can_mark_returned %}
        <div class="single-artists d-flex justify-content-center align-items-center wow fadeInUp mt-0 mb-15 m-auto" data-wow-delay="100ms">
            <a href="{% url 'product_create' %}" class="btn oneMusic-btn mt-30">Ingresar Nuevo Producto</a>
            <a href="{% url 'categories' %}" class="btn oneMusic-btn mt-30">Ver todas las Categorías </a>
            <a href="{% url 'category_create' %}" class="btn oneMusic-btn mt-30">Crear Categoría </a>
        </div>
    {% endif %}

  <table class="table text-center">
      <thead class="thead-dark">
          <tr>
              <th>Titulo</th>
              <th>Tipo</th>
              <th>Categoría</th>
              <th>Código</th>
              <th>Ver</th>
              {% if perms.catalog.can_mark_returned %}
                <th>Eliminar</th>
              {% endif %}

          </tr>
      </thead>
      <tbody>
      {% if product_list %}
          {% for product in product_list %}
              <tr>
                <td>{{ product.title }}</td>
                <td>{{ product.get_type_display }}</td>
                <td>{{ product.category }}</td>
                <td>{{ product.id }}</td>
                <td><a href="{{ product.get_absolute_url }}">Click</a></td>
                 {% if perms.catalog.can_mark_returned %}
                    <td><a href="{{ product.get_absolute_url }}/delete">X</a></td>
                 {% endif %}

              </tr>
          {% endfor %}
      {% endif %}
      </tbody>
  </table>
    <div class="single-artists d-flex justify-content-center align-items-center wow fadeInUp mt-0 mb-15 m-auto" data-wow-delay="100ms">
        <a href="{% url 'index' %}" class="btn oneMusic-btn mt-30">Regresar </a>
    </div>
</div>
{% endblock %}

haytunes/templates/haytunes/profile.html
{% extends 'base_generic.html' %}
<header class="header-area">
    {% block navbar %}
        {% include 'base_nav.html' %}
    {% endblock %}
</header>
{% block pagina_titulo %}
    <p>See what’s new</p>
    <h2>Perfil</h2>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
    {% if user.is_authenticated %}
        <h2>{{ user.get_full_name }}</h2>
        <table class="table text-center">
      <thead class="thead-dark">
          <tr>
              <th>Username</th>
              <th>Código</th>
              <th>Saldo</th>
          </tr>
      </thead>
      <tbody>
              <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.id }}</td>
                <td>{{ user.profile.credit }}</td>
                <td>{{ product.id }}</td>
              </tr>
      </tbody>
  </table>
    {% else %}
        <p>Please login to see this page.</p>
    {% endif %}

    <div class="single-artists d-flex justify-content-center align-items-center wow fadeInUp mt-0 mb-15 m-auto" data-wow-delay="100ms">
        <a href="{% url 'index' %}" class="btn oneMusic-btn mt-30">Regresar </a>
        <a href="{% url 'update_profile' %}" class="btn oneMusic-btn mt-30">Actualizar Datos</a>
    </div>
</div>
{% endblock %}

haytunes/templates/haytunes/update_profile.html
{% extends 'base_generic.html' %}
{% block content %}
    <form method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  <button type="submit">Save changes</button>
</form>
{% endblock %}